### ISSUE TITLE
Implement a user authentication

### ISSUE THREAD

**Issue by demon-xxi** [getryft/ryft-apidemo#34]
ii) Implement a user authentication (need to determine how complex this needs to be, ie simple File or LDAP)
- [ ] Implement LDAP authentication
- [ ] User id will restrict the visibility to dataset based on the Linux userid permission settings. 
  @adleyva  Last feature requires corresponding support on API side but it is not there and can't be implemented easily until we introduce SSO type of security.

**Comment by adleyva** [comment]
I have confirmed that the File system today does not enforce the privileges.  That said, would it be possible that the file discovery process could enforce own & group permissions on its own in conjunction with the LDAP authentication.

The issue are these cloud providers who need to support multi-tenancy operations which fundamentally is “isolating their data from the next customers”.

Do they want it per user or per account? (FULL ISOLATION is the ANSWER)
If looking at scenario of reusing same ryft box by several accounts, we can actually spin multiple instances of rest api and corresponding web ui having root folder to be configured for subfolder of /ryftone.

It is a parameter in rest api and right now we expose all files in the /ryftone. But we can go and make subfolders for each tenant. And then it will be a full isolation.
